USE polymerdb;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Polymer_data;
DROP TABLE IF EXISTS Tg_models;
DROP TABLE IF EXISTS FFV_models;
DROP TABLE IF EXISTS Tc_models;
DROP TABLE IF EXISTS Density_models;
DROP TABLE IF EXISTS Rg_models;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE Polymer_data(
    id INT AUTO_INCREMENT PRIMARY KEY,
    SMILES VARCHAR(255) NOT NULL,
    features JSON NOT NULL,
    Tg FLOAT NOT NULL,
    FFV FLOAT NOT NULL,
    Density FLOAT NOT NULL,
    Tc FLOAT NOT NULL,
    Rg FLOAT NOT NULL
);

CREATE TABLE Tg_models(
    id INT AUTO_INCREMENT PRIMARY KEY,
    version INT NOT NULL,
    MAE FLOAT NOT NULL,
    MSE FLOAT NOT NULL,
    RMSE FLOAT NOT NULL,
    R2 FLOAT NOT NULL,
    EVS FLOAT NOT NULL
);

CREATE TABLE FFV_models(
    id INT AUTO_INCREMENT PRIMARY KEY,
    version INT NOT NULL,
    MAE FLOAT NOT NULL,
    MSE FLOAT NOT NULL,
    RMSE FLOAT NOT NULL,
    R2 FLOAT NOT NULL,
    EVS FLOAT NOT NULL
);
CREATE TABLE Tc_models(
    id INT AUTO_INCREMENT PRIMARY KEY,
    version INT NOT NULL,
    MAE FLOAT NOT NULL,
    MSE FLOAT NOT NULL,
    RMSE FLOAT NOT NULL,
    R2 FLOAT NOT NULL,
    EVS FLOAT NOT NULL
);
CREATE TABLE Density_models(
    id INT AUTO_INCREMENT PRIMARY KEY,
    version INT NOT NULL,
    MAE FLOAT NOT NULL,
    MSE FLOAT NOT NULL,
    RMSE FLOAT NOT NULL,
    R2 FLOAT NOT NULL,
    EVS FLOAT NOT NULL
);
CREATE TABLE Rg_models(
    id INT AUTO_INCREMENT PRIMARY KEY,
    version INT NOT NULL,
    MAE FLOAT NOT NULL,
    MSE FLOAT NOT NULL,
    RMSE FLOAT NOT NULL,
    R2 FLOAT NOT NULL,
    EVS FLOAT NOT NULL
);